spring:
  application:
    name: PaginationAndSorting
    
    
  datasource:
    url: jdbc:postgresql://localhost:5432/Poc
    username: postgres
    password: vfire
    driver-class-name: org.postgresql.Driver
    
    
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: update
  
